// "Write it" button on every News Monitor alert card: drafts an article from
// that one scan result on demand, using the same generator as the automatic
// rating-4/5 breaking drafts (api/_breaking-draft.js), saves it as an
// Editorial Desk draft and returns its id so the page can open the Content
// Editor straight to it (/editor#3/<id>).
//
// If that story already has a draft (auto-drafted by rolling-digest/x-scan,
// or someone clicked Write it earlier) the existing one is returned instead
// of spending credits on a duplicate.
var S = require('./_supabase.js');
var Drafts = require('./_drafts.js');
var BreakingDraft = require('./_breaking-draft.js');
var Settings = require('./_settings-store.js');

function mdToHtml(t) {
  var s = String(t || '')
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g, '<a href="$2">$1</a>')
    .replace(/\*\*([^*]+)\*\*/g, '<b>$1</b>');
  return s.split(/\n\s*\n/).map(function(p) { return '<p>' + p.replace(/\n/g, '<br>') + '</p>'; }).filter(Boolean).join('\n');
}

module.exports = async function handler(req, res) {
  var auth;
  try { auth = await S.requireUserOrCron(req, res); }
  catch (authErr) { return res.status(authErr.status || 401).json({ error: authErr.message || 'Not signed in' }); }
  if (req.method !== 'POST') return res.status(405).json({ error: 'POST only' });
  if (!(await require('./_access').allowed(auth, 'act_write_story'))) return require('./_access').deny(res);

  var a = (req.body && req.body.alert) || {};
  if (!a.headline) return res.status(400).json({ error: 'alert.headline required' });
  var story = {
    headline: String(a.headline).slice(0, 500),
    summary: String(a.summary || '').slice(0, 3000),
    source: String(a.source || '').slice(0, 200),
    time: String(a.time || '').slice(0, 100),
    category: String(a.category || '').slice(0, 50),
    url: a.url ? String(a.url).slice(0, 2000) : ''
  };

  try {
    if (story.url) {
      var existing = await Drafts.findBySourceUrl(story.url);
      if (existing) return res.status(200).json({ id: existing.id, existing: true });
    }

    var houseStyle = S.isConfigured() ? await Settings.getHouseStyle(S.admin()) : null;
    var draft = await BreakingDraft.generateBreakingDraft(story, houseStyle);
    var id = Date.now().toString(36) + Math.random().toString(36).slice(2, 8);
    var now = new Date().toISOString();
    var requester = auth && auth.user && auth.user.email;
    await Drafts.saveDraft({
      id: id, writerName: 'AI draft (Write it)' + (requester ? ' for ' + requester : ''), tier: 'free',
      headline: draft.headline, headlines: [{ label: '', text: draft.headline }],
      html: mdToHtml(draft.edited), notes: draft.notes, factsToCheck: draft.factsToCheck,
      sourceUrl: story.url || null, autoGenerated: true, ownerId: (auth && auth.user && auth.user.id) || null, ownerEmail: requester || null,
      status: 'draft', createdAt: now, updatedAt: now
    });
    return res.status(200).json({ id: id, headline: draft.headline });
  } catch (e) {
    return res.status(500).json({ error: e.message });
  }
};
